### ISSUE TITLE
Messaging Rooms with MongoDB and WebSockets

### ISSUE THREAD

**Issue by AbdulGhani002** [p0syd0n/Mount-Olympus#1]
Change the messaging room feature using MongoDB for data storage and WebSockets for real-time messaging.
- Make mongodb in use and connect it to mongodv atlas.
- Make functionality of sending messages with websockets to send packets faster and hence optimize our whole app.

**Comment by p0syd0n** [comment]
MongoDB in the future is realistic, seeing as I can't always rely on SQLite. However, DM's and chatrooms already use sockets.
