### ISSUE TITLE
RSA 256 is very much not quantum proof

### ISSUE THREAD

**Issue by kcoderhtml** [p0syd0n/Mount-Olympus#3]

**Comment by kcoderhtml** [comment]
@p0syd0n thats rather misleading

**Comment by p0syd0n** [comment]
Yes, there are no assymetric encryption schemas that are quantum proof and useable on the browser side unfortunately. However, the AES 256 aspect is quantum proof, and the AES 256 blanket encrypts most of the data in the database on top of the RSA.

**Comment by kcoderhtml** [comment]
Ah that makes more sense. It might be good to state that on the README. Also AES 255 isnt quantum proof only quantum resistant. [This](https://eprint.iacr.org/2019/272.pdf) study for example was able to reduce a AES-256 attack to 7 rounds which while it would still take some time to break it isn’t unbreakable.
